import Fuse from 'fuse.js';

const general_chatbot_questions = [
      "Hi there!",
      "How are you doing today?",
      "What's the weather like?",
      "Tell me a fun fact.",
      "Can you help me with something?",
      "What's your name?",
      "How old are you?",
      "Where are you from?",
      "What can you do?",
      "Tell me a joke.",
      "What's the capital of France?",
      "Who won the last Super Bowl?",
      "What time is it?",
      "Set a timer for 10 minutes.",
      "Remind me to call John at 3 PM.",
      "What's on my calendar today?",
      "Play some music.",
      "What's the news?",
      "How do I cook a perfect steak?",
      "What's the best way to learn a new language?",
      "Suggest a good book.",
      "Recommend a movie.",
      "What's your favorite color?",
      "Do you have feelings?",
      "Are you human?",
      "What's the meaning of life?",
      "Can you write a poem?",
      "Translate 'hello' into Spanish.",
      "What's a good workout routine?",
      "How can I improve my focus?",
      "Tell me about artificial intelligence.",
      "What's the difference between AI and machine learning?",
      "Explain quantum physics simply.",
      "What's the latest in space exploration?",
      "How does a cryptocurrency work?",
      "What's blockchain technology?",
      "Give me some healthy snack ideas.",
      "How do I meditate?",
      "What's a good way to relieve stress?",
      "Tell me a story.",
      "What's your purpose?",
      "Are you always learning?",
      "Do you have opinions?",
      "What's your favorite animal?",
      "What's your favorite food?",
      "Can you mimic a cat?",
      "Sing me a song.",
      "What's the latest tech gadget?",
      "How do I fix a leaky faucet?",
      "What's the best internet browser?",
      "How to clear cache on my phone?",
      "Suggest a good podcast.",
      "What's a popular TV show right now?",
      "How to make coffee?",
      "What's the best way to organize my day?",
      "Give me some productivity tips.",
      "How do I create a budget?",
      "What are common investment mistakes?",
      "Explain stocks and bonds.",
      "What's a mutual fund?",
      "How do I save for retirement?",
      "What's the difference between a debit and credit card?",
      "How to improve my public speaking?",
      "Give me tips for a job interview.",
      "How to write a good resume?",
      "What's networking?",
      "How can I be more confident?",
      "What's a growth mindset?",
      "Tell me about positive psychology.",
      "How to deal with difficult people?",
      "What's emotional intelligence?",
      "Suggest a new hobby.",
      "What's the best way to travel on a budget?",
      "Recommend a travel destination.",
      "What are some famous landmarks?",
      "Tell me about ancient history.",
      "Who was Albert Einstein?",
      "What's the theory of relativity?",
      "Explain natural selection.",
      "What's photosynthesis?",
      "How do plants grow?",
      "What's the water cycle?",
      "Tell me about renewable energy.",
      "What's solar power?",
      "How does wind energy work?",
      "What's a sustainable lifestyle?",
      "Give me eco-friendly tips.",
      "How to recycle properly?",
      "What's climate change?",
      "Tell me about ocean conservation.",
      "What are endangered species?",
      "How can I help protect animals?",
      "Suggest some volunteer opportunities.",
      "What's mindfulness?",
      "How to practice gratitude?",
      "What's imposter syndrome?",
      "How to overcome procrastination?",
      "Give me motivation.",
      "What's a good morning routine?",
      "How to get better sleep?",
      "What's the ideal diet?",
      "Tell me about gut health.",
      "What are probiotics?",
      "How to boost my immune system?",
      "What's a balanced diet?",
      "Give me healthy recipe ideas.",
      "How to meal prep?",
      "What's strength training?",
      "How often should I exercise?",
      "What's cardiovascular exercise?",
      "Tell me about yoga benefits.",
      "How to stretch properly?",
      "What's good posture?",
      "How to relieve back pain?",
      "What's ergonomics?",
      "Suggest a good podcast about health.",
      "What's the history of computers?",
      "Who invented the internet?",
      "How does a search engine work?",
      "What's a URL?",
      "What's an IP address?",
      "How to protect my online privacy?",
      "What's phishing?",
      "How to create a strong password?",
      "What's two-factor authentication?",
      "Tell me about cybersecurity.",
      "What's a firewall?",
      "How to update my software?",
      "What's a computer virus?",
      "How to remove malware?",
      "What's cloud computing?",
      "How does streaming work?",
      "What's an API?",
      "Explain big data.",
      "What's data analytics?",
      "How is data visualization important?",
      "What's a database?",
      "How does a network function?",
      "What's Wi-Fi?",
      "How to troubleshoot internet connection?",
      "What's a router?",
      "Explain operating systems.",
      "What's Windows?",
      "What's macOS?",
      "What's Linux?",
      "Tell me about mobile operating systems.",
      "What's Android?",
      "What's iOS?",
      "How do apps work?",
      "What's software development?",
      "What's a programming language?",
      "Tell me about Python.",
      "What's JavaScript?",
      "What's HTML and CSS?",
      "How to build a website?",
      "What's web design?",
      "What's user experience (UX)?",
      "What's user interface (UI)?",
      "Tell me about graphic design.",
      "What's photo editing?",
      "How to make a video?",
      "What's video editing software?",
      "Tell me about animation.",
      "What's virtual reality (VR)?",
      "What's augmented reality (AR)?",
      "How does a 3D printer work?",
      "What's robotics?",
      "Tell me about self-driving cars.",
      "What's smart home technology?",
      "How do smart assistants work?",
      "What's the Internet of Things (IoT)?",
      "Tell me about digital marketing.",
      "What's SEO?",
      "How does social media marketing work?",
      "What's content marketing?",
      "What's email marketing?",
      "How to run online ads?",
      "What's analytics in marketing?",
      "Tell me about e-commerce.",
      "How to start an online store?",
      "What's payment processing?",
      "What's logistics in e-commerce?",
      "How to handle customer service online?",
      "What's an online marketplace?",
      "Tell me about entrepreneurship.",
      "How to start a business?",
      "What's a business plan?",
      "How to get funding for a startup?",
      "What's venture capital?",
      "What's angel investing?",
      "How to market a new product?",
      "What's branding?",
      "How to build a strong brand?",
      "What's customer loyalty?",
      "How to get customer feedback?",
      "What's product development?",
      "What's quality control?",
      "Tell me about supply chain management.",
      "What's inventory management?",
      "How to manage a team?",
      "What's leadership?",
      "How to motivate employees?",
      "What's team building?",
      "How to resolve conflicts at work?",
      "What's workplace culture?",
      "Tell me about professional development.",
      "How to learn new skills?",
      "What's a mentor?",
      "How to network professionally?",
      "What's emotional intelligence in the workplace?",
      "How to manage stress at work?",
      "What's work-life balance?",
      "How to set boundaries?",
      "Tell me about personal finance.",
      "How to save money?",
      "What's a good credit score?",
      "How to improve my credit score?",
      "What's debt management?",
      "How to pay off student loans?",
      "What's a mortgage?",
      "How to buy a house?",
      "What's insurance?",
      "Tell me about different types of insurance.",
      "What's estate planning?",
      "How to write a will?",
      "What's power of attorney?",
      "Tell me about taxes.",
      "How to file my taxes?",
      "What are common tax deductions?",
      "What's financial literacy?",
      "How to make smart financial decisions?",
      "What's a budget spreadsheet?",
      "How to track my expenses?",
      "What's a sinking fund?",
      "How to save for a big purchase?",
      "What's emergency savings?",
      "How much should I save?",
      "What's compound interest?",
      "Tell me about investing basics.",
      "What's diversification?",
      "How to choose an investment advisor?",
      "What's a Roth IRA?",
      "What's a 401k?",
      "Tell me about real estate investing.",
      "What's passive income?",
      "How to start a side hustle?",
      "What's freelance work?",
      "How to find freelance clients?",
      "What's a contract?",
      "How to negotiate a contract?",
      "What's intellectual property?",
      "How to protect my ideas?",
      "What's a patent?",
      "What's a trademark?",
      "What's copyright?",
      "Tell me about legal agreements.",
      "What's a non-disclosure agreement?",
      "What's a terms of service agreement?",
      "How to understand legal jargon?",
      "What's conflict resolution?",
      "How to mediate a dispute?",
      "What's negotiation skills?",
      "How to communicate effectively?",
      "What's active listening?",
      "How to give constructive feedback?",
      "What's assertiveness?",
      "How to build strong relationships?",
      "What's empathy?",
      "How to show appreciation?",
      "What's forgiveness?",
      "How to practice self-compassion?",
      "What's resilience?",
      "How to bounce back from setbacks?",
      "What's optimism?",
      "How to cultivate happiness?",
      "What's gratitude journaling?",
      "How to find purpose?",
      "What's spiritual wellness?",
      "How to connect with nature?",
      "What's environmental awareness?",
      "How to be a good global citizen?",
      "What's cultural sensitivity?",
      "How to learn about other cultures?",
      "What's social justice?",
      "How to advocate for change?",
      "What's community engagement?",
      "How to volunteer locally?",
      "What's civic responsibility?",
      "How to participate in democracy?",
      "What's critical thinking?",
      "How to solve problems creatively?",
      "What's decision-making?",
      "How to analyze information?",
      "What's research skills?",
      "How to evaluate sources?",
      "What's academic writing?",
      "How to cite sources?",
      "What's plagiarism?",
      "How to avoid plagiarism?",
      "What's academic integrity?",
      "How to study effectively?",
      "What's memory improvement?",
      "How to prepare for exams?",
      "What's lifelong learning?",
      "How to stay curious?",
      "What's personal growth?",
      "How to reflect on my experiences?",
      "What's self-awareness?",
      "How to understand my strengths?",
      "What's my personality type?",
      "How to understand my weaknesses?",
      "What's self-improvement?",
      "How to set goals?",
      "What's goal setting frameworks?",
      "How to stay accountable?",
      "What's discipline?",
      "How to build good habits?",
      "What's habit tracking?",
      "How to break bad habits?",
      "What's consistency?",
      "How to overcome challenges?",
      "What's perseverance?",
      "How to manage expectations?",
      "What's patience?",
      "How to find inner peace?",
      "What's meditation techniques?",
      "How to practice mindfulness daily?",
      "What's deep breathing exercises?",
      "How to calm my mind?",
      "What's relaxation techniques?",
      "How to relieve tension?",
      "What's self-care practices?",
      "How to prioritize my well-being?",
      "What's emotional regulation?",
      "How to manage anger?",
      "What's anxiety relief?",
      "How to cope with sadness?",
      "What's resilience in mental health?",
      "How to seek professional help?",
      "What's therapy options?",
      "How to support mental health awareness?",
      "What's stigma surrounding mental illness?",
      "How to promote a positive body image?",
      "What's healthy eating habits?",
      "How to maintain a healthy weight?",
      "What's regular physical activity?",
      "How to improve my sleep hygiene?",
      "What's stress management techniques?",
      "How to build healthy relationships?",
      "What's effective communication in relationships?",
      "How to resolve conflicts constructively?",
      "What's setting boundaries in relationships?",
      "How to show appreciation to loved ones?",
      "What's quality time with family?",
      "How to build strong friendships?",
      "What's supportive networks?",
      "How to ask for help?",
      "What's giving back to the community?",
      "How to be a good neighbor?",
      "What's civic engagement?",
      "How to participate in local events?",
      "What's environmental stewardship?",
      "How to reduce my carbon footprint?",
      "What's responsible consumption?",
      "How to minimize waste?",
      "What's ethical consumerism?",
      "How to support sustainable businesses?",
      "What's fair trade?",
      "How to learn about global issues?",
      "What's humanitarian aid?",
      "How to contribute to global well-being?",
      "What's cultural exchange?",
      "How to learn a new language?",
      "What's exploring different cuisines?",
      "How to appreciate diverse art forms?",
      "What's understanding religious diversity?",
      "How to foster inclusion?",
      "What's empathy towards different perspectives?",
      "How to challenge my own biases?",
      "What's critical self-reflection?",
      "How to grow from mistakes?",
      "What's learning from feedback?",
      "How to stay open-minded?",
      "What's intellectual curiosity?",
      "How to pursue knowledge?",
      "What's creative expression?",
      "How to explore artistic outlets?",
      "What's playing a musical instrument?",
      "How to engage in visual arts?",
      "What's writing for self-expression?",
      "How to tell compelling stories?",
      "What's public speaking tips?",
      "How to present confidently?",
      "What's active listening in conversations?",
      "How to ask clarifying questions?",
      "What's non-verbal communication?",
      "How to interpret body language?",
      "What's building rapport?",
      "How to connect with new people?",
      "What's networking strategies?",
      "How to maintain professional relationships?",
      "What's mentorship opportunities?",
      "How to find a mentor?",
      "What's being a mentor?",
      "How to develop leadership skills?",
      "What's effective delegation?",
      "How to motivate a team?",
      "What's managing projects?",
      "How to set project goals?",
      "What's time management techniques?",
      "How to prioritize tasks?",
      "What's avoiding procrastination?",
      "How to stay organized?",
      "What's digital detox?",
      "How to reduce screen time?",
      "What's finding balance with technology?",
      "How to protect against cyber threats?",
      "What's online privacy best practices?",
      "How to manage digital footprint?",
      "What's understanding data security?",
      "How to use strong passwords?",
      "What's two-factor authentication benefits?",
      "How to identify phishing scams?",
      "What's safe browsing habits?",
      "How to update software regularly?",
      "What's backing up important data?",
      "How to use cloud storage securely?",
      "What's understanding software licenses?",
      "How to choose reliable apps?",
      "What's troubleshooting common tech issues?",
      "How to optimize device performance?",
      "What's learning coding basics?",
      "How to understand algorithms?",
      "What's introduction to AI concepts?",
      "How to use AI tools responsibly?",
      "What's ethical considerations in AI?",
      "How to learn about robotics?",
      "What's smart home device advantages?",
      "How to set up a smart home?",
      "What's understanding IoT security?",
      "How to use virtual reality experiences?",
      "What's augmented reality applications?",
      "How to explore 3D printing possibilities?",
      "What's digital art creation?",
      "How to use graphic design software?",
      "What's video editing for beginners?",
      "How to start a podcast?",
      "What's creating engaging content?",
      "How to build an online presence?",
      "What's social media strategy?",
      "How to grow an audience online?",
      "What's email newsletter best practices?",
      "How to optimize for search engines?",
      "What's content marketing trends?",
      "How to analyze website traffic?",
      "What's understanding conversion rates?",
      "How to run effective online ads?",
      "What's digital marketing analytics?",
      "How to build an e-commerce website?",
      "What's product photography tips?",
      "How to write compelling product descriptions?",
      "What's secure payment gateways?",
      "How to manage online orders?",
      "What's shipping and fulfillment options?",
      "How to handle customer returns?",
      "What's customer support strategies?",
      "How to build customer loyalty online?",
      "What's online review management?",
      "How to respond to negative reviews?",
      "What's reputation management online?",
      "How to use social listening tools?",
      "What's influencer marketing?",
      "How to collaborate with influencers?",
      "What's affiliate marketing strategies?",
      "How to track affiliate performance?",
      "What's content syndication?",
      "How to repurpose content?",
      "What's building a content calendar?",
      "How to measure content ROI?",
      "What's lead generation tactics?",
      "How to nurture leads?",
      "What's sales funnel optimization?",
      "How to close more sales?",
      "What's customer relationship management (CRM)?",
      "How to use CRM software?",
      "What's marketing automation?",
      "How to set up automated email campaigns?",
      "What's A/B testing in marketing?",
      "How to improve website conversion?",
      "What's landing page optimization?",
      "How to create effective calls to action?",
      "What's understanding user behavior analytics?",
      "How to use heatmaps and session recordings?",
      "What's web accessibility guidelines?",
      "How to make websites accessible?",
      "What's mobile-first design?",
      "How to optimize for mobile devices?",
      "What's progressive web apps?",
      "How to develop cross-platform apps?",
      "What's responsive web design?",
      "How to ensure website performance?",
      "What's website security best practices?",
      "How to prevent DDoS attacks?",
      "What's SSL certificates?",
      "How to protect sensitive data online?",
      "What's data encryption?",
      "How to comply with data privacy regulations?",
      "What's GDPR implications?",
      "How to ensure CCPA compliance?",
      "What's data governance?",
      "How to manage data quality?",
      "What's data warehousing?",
      "How to build a data lake?",
      "What's business intelligence tools?",
      "How to create dashboards?",
      "What's reporting and analytics?",
      "How to interpret business metrics?",
      "What's key performance indicators (KPIs)?",
      "How to set meaningful KPIs?",
      "What's strategic planning?",
      "How to develop a business strategy?",
      "What's competitive analysis?",
      "How to identify market trends?",
      "What's market research methods?",
      "How to conduct customer surveys?",
      "What's focus group moderation?",
      "How to analyze market data?",
      "What's product market fit?",
      "How to test product ideas?",
      "What's minimum viable product (MVP)?",
      "How to iterate on product development?",
      "What's user testing techniques?",
      "How to gather user feedback effectively?",
      "What's agile development methodology?",
      "How to implement Scrum?",
      "What's Kanban framework?",
      "How to manage software projects?",
      "What's quality assurance in software?",
      "How to conduct software testing?",
      "What's continuous integration/delivery (CI/CD)?",
      "How to automate deployment?",
      "What's DevOps practices?",
      "How to streamline development operations?",
      "What's containerization with Docker?",
      "How to orchestrate containers with Kubernetes?",
      "What's serverless computing?",
      "How to use AWS Lambda?",
      "What's Google Cloud Functions?",
      "How to deploy applications to Azure Functions?",
      "What's microservices architecture?",
      "How to design distributed systems?",
      "What's API management?",
      "How to secure APIs?",
      "What's event-driven architecture?",
      "How to use message queues?",
      "What's real-time data processing?",
      "How to build streaming applications?",
      "What's machine learning operations (MLOps)?",
      "How to deploy ML models?",
      "What's model monitoring?",
      "How to retrain ML models?",
      "What's explainable AI (XAI)?",
      "How to interpret AI decisions?",
      "What's fairness in AI?",
      "How to address bias in AI?",
      "What's privacy-preserving AI?",
      "How to anonymize data for AI?",
      "What's federated learning?",
      "How to use differential privacy?",
      "What's synthetic data generation?",
      "How to augment datasets?",
      "What's transfer learning?",
      "How to fine-tune pre-trained models?",
      "What's reinforcement learning applications?",
      "How to train agents?",
      "What's natural language processing (NLP)?",
      "How to build chatbots?",
      "What's sentiment analysis?",
      "How to extract entities from text?",
      "What's text summarization?",
      "How to generate human-like text?",
      "What's computer vision?",
      "How to detect objects in images?",
      "What's facial recognition technology?",
      "How to analyze video content?",
      "What's image generation models?",
      "How to create realistic images?",
      "What's generative adversarial networks (GANs)?",
      "How to use diffusion models?",
      "What's speech recognition?",
      "How to convert speech to text?",
      "What's text-to-speech synthesis?",
      "How to create voice assistants?",
      "What's robotics process automation (RPA)?",
      "How to automate repetitive tasks?",
      "What's intelligent automation?",
      "How to combine AI and RPA?",
      "What's blockchain in supply chain?",
      "How to use smart contracts?",
      "What's decentralized finance (DeFi)?",
      "How to understand NFTs?",
      "What's metaverse applications?",
      "How to explore virtual worlds?",
      "What's immersive experiences?",
      "How to develop VR/AR content?",
      "What's quantum computing basics?",
      "How does quantum entanglement work?",
      "What's quantum supremacy?",
      "How will quantum computing impact industries?",
      "What's bioinformatics?",
      "How to analyze genomic data?",
      "What's drug discovery with AI?",
      "How to personalize medicine?",
      "What's smart city initiatives?",
      "How to improve urban planning with data?",
      "What's IoT in smart cities?",
      "How to enhance public safety with technology?",
      "What's precision agriculture?",
      "How to use drones in farming?",
      "What's AI for crop optimization?",
      "How to manage water resources effectively?",
      "What's renewable energy management?",
      "How to optimize smart grids?",
      "What's energy storage solutions?",
      "How to predict energy consumption?",
      "What's sustainable manufacturing?",
      "How to reduce waste in production?",
      "What's circular economy principles?",
      "How to design for recyclability?",
      "What's ethical sourcing?",
      "How to ensure fair labor practices?",
      "What's supply chain transparency?",
      "How to trace products with blockchain?",
      "What's digital twin technology?",
      "How to create virtual models of assets?",
      "What's predictive maintenance?",
      "How to anticipate equipment failures?",
      "What's industrial IoT (IIoT)?",
      "How to connect factory devices?",
      "What's real-time operational intelligence?",
      "How to optimize manufacturing processes?",
      "What's lean manufacturing principles?",
      "How to eliminate waste in production?",
      "What's Six Sigma methodology?",
      "How to improve process quality?",
      "What's total quality management (TQM)?",
      "How to foster continuous improvement?",
      "What's change management strategies?",
      "How to implement organizational change?",
      "What's fostering innovation in the workplace?",
      "How to encourage creativity?",
      "What's design thinking process?",
      "How to apply design thinking to problems?",
      "What's user-centered design?",
      "How to conduct usability testing?",
      "What's A/B testing user interfaces?",
      "How to optimize user experience?",
      "What's customer journey mapping?",
      "How to understand customer touchpoints?",
      "What's personalized customer experiences?",
      "How to use AI for customer segmentation?",
      "What's hyper-personalization in marketing?",
      "How to deliver tailored content?",
      "What's customer feedback loops?",
      "How to integrate feedback into products?",
      "What's service design?",
      "How to design holistic services?",
      "What's digital transformation strategies?",
      "How to implement digital initiatives?",
      "What's organizational agility?",
      "How to adapt to market changes?",
      "What's future of work trends?",
      "How to prepare for automation?",
      "What's upskilling and reskilling?",
      "How to embrace continuous learning?",
      "What's remote work best practices?",
      "How to manage virtual teams?",
      "What's hybrid work models?",
      "How to foster collaboration remotely?",
      "What's digital workplace tools?",
      "How to use communication platforms?",
      "What's virtual meeting etiquette?",
      "How to run effective online meetings?",
      "What's employee engagement strategies?",
      "How to boost morale in remote teams?",
      "What's performance management in a hybrid environment?",
      "How to set clear expectations remotely?",
      "What's employee well-being initiatives?",
      "How to support mental health at work?",
      "What's diversity, equity, and inclusion (DEI) initiatives?",
      "How to create an inclusive workplace?",
      "What's unconscious bias training?",
      "How to promote equitable opportunities?",
      "What's ethical leadership?",
      "How to lead with integrity?",
      "What's corporate social responsibility (CSR)?",
      "How to implement CSR programs?",
      "What's sustainability reporting?",
      "How to measure environmental impact?",
      "What's social impact investing?",
      "How to align investments with values?",
      "What's impact measurement?",
      "How to assess social outcomes?",
      "What's philanthropy strategies?",
      "How to maximize charitable giving?",
      "What's grant writing tips?",
      "How to secure funding for non-profits?",
      "What's social entrepreneurship?",
      "How to build a business with social impact?",
      "What's venture philanthropy?",
      "How to support social enterprises?",
      "What's microfinance initiatives?",
      "How to provide small loans?",
      "What's financial inclusion?",
      "How to serve underserved communities?",
      "What's digital literacy programs?",
      "How to bridge the digital divide?",
      "What's educational technology (EdTech)?",
      "How to use technology for learning?",
      "What's personalized learning paths?",
      "How to adapt education to individual needs?",
      "What's gamification in education?",
      "How to make learning engaging?",
      "What's augmented reality in classrooms?",
      "How to create interactive learning experiences?",
      "What's virtual labs?",
      "How to simulate experiments virtually?",
      "What's AI in educational assessment?",
      "How to provide automated feedback?",
      "What's learning analytics?",
      "How to track student progress?",
      "What's adaptive learning platforms?",
      "How to customize learning content?",
      "What's open educational resources (OER)?",
      "How to access free learning materials?",
      "What's massive open online courses (MOOCs)?",
      "How to take online university courses?",
      "What's professional certifications?",
      "How to enhance career prospects?",
      "What's skills-based hiring?",
      "How to demonstrate competency?",
      "What's competency frameworks?",
      "How to define required skills?",
      "What's talent development programs?",
      "How to upskill employees?",
      "What's leadership development programs?",
      "How to train future leaders?",
      "What's succession planning?",
      "How to prepare for leadership transitions?",
      "What's organizational development?",
      "How to improve organizational effectiveness?",
      "What's performance appraisals?",
      "How to conduct employee reviews?",
      "What's 360-degree feedback?",
      "How to gather comprehensive feedback?",
      "What's employee recognition programs?",
      "How to appreciate employee contributions?",
      "What's incentive programs?",
      "How to motivate high performance?",
      "What's employee wellness programs?",
      "How to promote employee health?",
      "What's mental health support in the workplace?",
      "How to destigmatize mental illness at work?",
      "What's crisis management for businesses?",
      "How to prepare for emergencies?",
      "What's business continuity planning?",
      "How to ensure operations during disruptions?",
      "What's risk assessment strategies?",
      "How to identify potential risks?",
      "What's mitigation planning?",
      "How to reduce risk impact?",
      "What's cybersecurity insurance?",
      "How to protect against cyber attacks?",
      "What's data breach response plan?",
      "How to handle a data breach?",
      "What's compliance regulations?",
      "How to adhere to industry standards?",
      "What's regulatory compliance software?",
      "How to automate compliance checks?",
      "What's legal counsel for businesses?",
      "How to seek legal advice?",
      "What's intellectual property protection for businesses?",
      "How to safeguard business innovations?",
      "What's contract drafting best practices?",
      "How to create legally sound agreements?",
      "What's dispute resolution for businesses?",
      "How to resolve commercial disputes?",
      "What's alternative dispute resolution (ADR)?",
      "How to use mediation and arbitration?",
      "What's business ethics policies?",
      "How to foster ethical conduct?",
      "What's corporate governance?",
      "How to ensure responsible leadership?",
      "What's stakeholder engagement?",
      "How to involve relevant parties?",
      "What's investor relations?",
      "How to communicate with investors?",
      "What's public relations strategies?",
      "How to manage public image?",
      "What's crisis communications?",
      "How to handle negative publicity?",
      "What's brand reputation management?",
      "How to build a positive brand image?",
      "What's media training?",
      "How to prepare for media interviews?",
      "What's social media crisis management?",
      "How to respond to social media backlash?",
      "What's influencer relations for brands?",
      "How to engage with key influencers?",
      "What's content strategy for PR?",
      "How to create compelling press releases?",
      "What's thought leadership development?",
      "How to position executives as experts?",
      "What's event marketing for businesses?",
      "How to plan successful events?",
      "What's trade show participation?",
      "How to maximize trade show ROI?",
      "What's experiential marketing?",
      "How to create memorable brand experiences?",
      "What's guerilla marketing tactics?",
      "How to generate buzz creatively?",
      "What's viral marketing strategies?",
      "How to create shareable content?",
      "What's brand storytelling?",
      "How to connect with customers emotionally?",
      "What's narrative marketing?",
      "How to craft engaging brand narratives?",
      "What's personalized marketing messages?",
      "How to tailor content to individual customers?",
      "What's omni-channel marketing?",
      "How to provide consistent brand experience?",
      "What's customer lifetime value (CLV)?",
      "How to increase CLV?",
      "What's customer churn prevention?",
      "How to retain existing customers?",
      "What's loyalty programs effectiveness?",
      "How to design effective loyalty programs?",
      "What's customer segmentation for marketing?",
      "How to target specific customer groups?",
      "What's market penetration strategies?",
      "How to enter new markets?",
      "What's market development strategies?",
      "How to expand existing markets?",
      "What's product development strategies" ]

const fuzz = new Fuse(general_chatbot_questions);
const result = fuzz.search("how");    
console.log(result);
